ALTER TABLE user_books
    MODIFY COLUMN status ENUM('QUERO_LER', 'LENDO', 'LIDO', 'ABANDONADO', 'QUERO_RELER') NOT NULL;

ALTER TABLE user_books ADD COLUMN favorite BOOLEAN NOT NULL DEFAULT FALSE AFTER rating;
