server.port=${SERVER_PORT:8082}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3309/biblioteca?connectionTimeZone=UTC&forceConnectionTimeZoneToSession=true}
spring.datasource.username=${DB_USERNAME:biblioteca}
spring.datasource.password=${DB_PASSWORD:biblioteca}

spring.jpa.show-sql=false

logging.level.com.isaborosa.biblioteca=DEBUG
