/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as BibliotecaIndexRouteImport } from './routes/biblioteca/index'
import { Route as BibliotecaEstatisticasRouteImport } from './routes/biblioteca/estatisticas'
import { Route as BibliotecaPesquisarRouteImport } from './routes/biblioteca/pesquisar'
import { Route as BibliotecaLivroIdRouteImport } from './routes/biblioteca/livro.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaIndexRoute = BibliotecaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BibliotecaRoute,
} as any)
const BibliotecaEstatisticasRoute = BibliotecaEstatisticasRouteImport.update({
  id: '/estatisticas',
  path: '/estatisticas',
  getParentRoute: () => BibliotecaRoute,
} as any)
const BibliotecaPesquisarRoute = BibliotecaPesquisarRouteImport.update({
  id: '/pesquisar',
  path: '/pesquisar',
  getParentRoute: () => BibliotecaRoute,
} as any)
const BibliotecaLivroIdRoute = BibliotecaLivroIdRouteImport.update({
  id: '/livro/$id',
  path: '/livro/$id',
  getParentRoute: () => BibliotecaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/biblioteca/estatisticas': typeof BibliotecaEstatisticasRoute
  '/biblioteca/pesquisar': typeof BibliotecaPesquisarRoute
  '/biblioteca/': typeof BibliotecaIndexRoute
  '/biblioteca/livro/$id': typeof BibliotecaLivroIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biblioteca/estatisticas': typeof BibliotecaEstatisticasRoute
  '/biblioteca/pesquisar': typeof BibliotecaPesquisarRoute
  '/biblioteca': typeof BibliotecaIndexRoute
  '/biblioteca/livro/$id': typeof BibliotecaLivroIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/biblioteca/estatisticas': typeof BibliotecaEstatisticasRoute
  '/biblioteca/pesquisar': typeof BibliotecaPesquisarRoute
  '/biblioteca/': typeof BibliotecaIndexRoute
  '/biblioteca/livro/$id': typeof BibliotecaLivroIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biblioteca'
    | '/biblioteca/estatisticas'
    | '/biblioteca/pesquisar'
    | '/biblioteca/'
    | '/biblioteca/livro/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biblioteca/estatisticas'
    | '/biblioteca/pesquisar'
    | '/biblioteca'
    | '/biblioteca/livro/$id'
  id:
    | '__root__'
    | '/'
    | '/biblioteca'
    | '/biblioteca/estatisticas'
    | '/biblioteca/pesquisar'
    | '/biblioteca/'
    | '/biblioteca/livro/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliotecaRoute: typeof BibliotecaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca/': {
      id: '/biblioteca/'
      path: '/'
      fullPath: '/biblioteca/'
      preLoaderRoute: typeof BibliotecaIndexRouteImport
      parentRoute: typeof BibliotecaRoute
    }
    '/biblioteca/estatisticas': {
      id: '/biblioteca/estatisticas'
      path: '/estatisticas'
      fullPath: '/biblioteca/estatisticas'
      preLoaderRoute: typeof BibliotecaEstatisticasRouteImport
      parentRoute: typeof BibliotecaRoute
    }
    '/biblioteca/pesquisar': {
      id: '/biblioteca/pesquisar'
      path: '/pesquisar'
      fullPath: '/biblioteca/pesquisar'
      preLoaderRoute: typeof BibliotecaPesquisarRouteImport
      parentRoute: typeof BibliotecaRoute
    }
    '/biblioteca/livro/$id': {
      id: '/biblioteca/livro/$id'
      path: '/livro/$id'
      fullPath: '/biblioteca/livro/$id'
      preLoaderRoute: typeof BibliotecaLivroIdRouteImport
      parentRoute: typeof BibliotecaRoute
    }
  }
}

interface BibliotecaRouteChildren {
  BibliotecaEstatisticasRoute: typeof BibliotecaEstatisticasRoute
  BibliotecaPesquisarRoute: typeof BibliotecaPesquisarRoute
  BibliotecaIndexRoute: typeof BibliotecaIndexRoute
  BibliotecaLivroIdRoute: typeof BibliotecaLivroIdRoute
}

const BibliotecaRouteChildren: BibliotecaRouteChildren = {
  BibliotecaEstatisticasRoute: BibliotecaEstatisticasRoute,
  BibliotecaPesquisarRoute: BibliotecaPesquisarRoute,
  BibliotecaIndexRoute: BibliotecaIndexRoute,
  BibliotecaLivroIdRoute: BibliotecaLivroIdRoute,
}

const BibliotecaRouteWithChildren = BibliotecaRoute._addFileChildren(
  BibliotecaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliotecaRoute: BibliotecaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
